name: Create Pull Request on Branch Creation

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          gh pr create --title "Pull Request for $BRANCH_NAME" --body "This PR is automatically created for the branch $BRANCH_NAME" --head $BRANCH_NAME --base main
